DRB = {
    "WORKS": {
        "Genesis": "Moses",
        "Exodus": "Moses",
        "Leviticus": "Moses",
        "Numbers": "Moses",
        "Deuteronomy": "Moses",
        "Joshua": "Joshua",
        "Judges": "Samuel",
        "Ruth": "Samuel",
        "1 Samuel": "Samuel",
        "2 Samuel": "Nathan",
        "1 Kings": "Jeremiah",
        "2 Kings": "Jeremiah",
        "1 Chronicles": "Ezra",
        "2 Chronicles": "Ezra",
        "Ezra": "Ezra",
        "Nehemiah": "Nehemiah",
        "Esther": "Mordecai",
        "Job": "Job",
        "Psalms": "David",
        "Proverbs": "Solomon",
        "Ecclesiastes": "Solomon",
        "Song of Songs": "Solomon",
        "Wisdom": "Solomon",
        "Sirach": "Sirach",
        "Isaiah": "Isaiah",
        "Jeremiah": "Jeremiah",
        "Lamentations": "Jeremiah",
        "Baruch": "Baruch",
        "Ezekiel": "Ezekiel",
        "Daniel": "Daniel",
        "Hosea": "Hosea",
        "Joel": "Joel",
        "Amos": "Amos",
        "Obadiah": "Obadiah",
        "Jonah": "Jonah",
        "Micah": "Micah",
        "Nahum": "Nahum",
        "Habakkuk": "Habakkuk",
        "Zephaniah": "Zephaniah",
        "Haggai": "Haggai",
        "Zechariah": "Zechariah",
        "Malachi": "Malachi",
        "1 Maccabees": "Unknown",
        "2 Maccabees": "Unknown",
        "Matthew": "Matthew",
        "Mark": "Mark",
        "Luke": "Luke",
        "John": "John",
        "Acts": "Luke",
        "Romans": "Paul",
        "1 Corinthians": "Paul",
        "2 Corinthians": "Paul",
        "Galatians": "Paul",
        "Ephesians": "Paul",
        "Philippians": "Paul",
        "Colossians": "Paul",
        "1 Thessalonians": "Paul",
        "2 Thessalonians": "Paul",
        "1 Timothy": "Paul",
        "2 Timothy": "Paul",
        "Titus": "Paul",
        "Philemon": "Paul",
        "Hebrews": "Paul",
        "James": "James",
        "1 Peter": "Peter",
        "2 Peter": "Peter",
        "1 John": "John",
        "2 John": "John",
        "3 John": "John",
        "Jude": "Jude",
        "Revelation": "John",
    },
    "WRITING_NODE_IDS": {
        "Genesis": "gen",
        "Exodus": "exo",
        "Leviticus": "lev",
        "Numbers": "num",
        "Deuteronomy": "deu",
        "Joshua": "jos",
        "Judges": "judg",
        "Ruth": "ruth",
        "1 Samuel": "sam1",
        "2 Samuel": "sam2",
        "1 Kings": "kgs1",
        "2 Kings": "kgs2",
        "1 Chronicles": "chr1",
        "2 Chronicles": "chr2",
        "Ezra": "ezra",
        "Nehemiah": "neh",
        "Esther": "est",
        "Job": "job",
        "Psalms": "psa",
        "Proverbs": "pro",
        "Ecclesiastes": "ecc",
        "Song of Songs": "song",
        "Wisdom": "wis",
        "Sirach": "sir",
        "Isaiah": "isa",
        "Jeremiah": "jer",
        "Lamentations": "lam",
        "Baruch": "bar",
        "Ezekiel": "eze",
        "Daniel": "dan",
        "Hosea": "hos",
        "Joel": "joel",
        "Amos": "amos",
        "Obadiah": "obad",
        "Jonah": "jonah",
        "Micah": "mic",
        "Nahum": "nah",
        "Habakkuk": "hab",
        "Zephaniah": "zeph",
        "Haggai": "hag",
        "Zechariah": "zech",
        "Malachi": "mal",
        "1 Maccabees": "mac1",
        "2 Maccabees": "mac2",
        "Matthew": "mat",
        "Mark": "mar",
        "Luke": "luk",
        "John": "joh",
        "Acts": "act",
        "Romans": "rom",
        "1 Corinthians": "cor1",
        "2 Corinthians": "cor2",
        "Galatians": "gal",
        "Ephesians": "eph",
        "Philippians": "phi",
        "Colossians": "col",
        "1 Thessalonians": "thes1",
        "2 Thessalonians": "thes2",
        "1 Timothy": "tim1",
        "2 Timothy": "tim2",
        "Titus": "tit",
        "Philemon": "phm",
        "Hebrews": "heb",
        "James": "jam",
        "1 Peter": "pet1",
        "2 Peter": "pet2",
        "1 John": "joh1",
        "2 John": "joh2",
        "3 John": "joh3",
        "Jude": "jud",
        "Revelation": "rev",
    },
}
