DRB = {
    "WORKS": {
        "Genesis": "Moses",
        "Exodus": "Moses",
        "Leviticus": "Moses",
        "Numbers": "Moses",
        "Deuteronomy": "Moses",
        "Josue": "Joshua",
        "Judges": "Samuel",
        "Ruth": "Samuel",
        "1 Samuel": "Samuel",
        "2 Samuel": "Nathan",
        "3 Kings": "Jeremiah",
        "4 Kings": "Jeremiah",
        "First Book of Paralipomenon": "Ezra",
        "Second Book of Paralipomenon": "Ezra",
        "1 Esdras": "Ezra",
        "2 Esdras": "Nehemiah",
        "Esther": "Mordecai",
        "Job": "Moses",
        "Psalms": "David",
        "Proverbs": "Solomon",
        "Ecclesiastes": "Solomon",
        "Solomon's Canticle of Canticles": "Solomon",
        "Wisdom": "Solomon",
        "Ecclesiasticus": "Sirach",
        "Prophecy of Isaias": "Isaiah",
        "Prophecy of Jeremias": "Jeremiah",
        "Lamentations of Jeremias": "Jeremiah",
        "Prophecy of Baruch": "Baruch",
        "Prophecy of Ezechiel": "Ezekiel",
        "Prophecy of Daniel": "Daniel",
        "Prophecy of Osee": "Hosea",
        "Prophecy of Joel": "Joel",
        "Prophecy of Amos": "Amos",
        "Prophecy of Abdias": "Obadiah",
        "Prophecy of Jonas": "Jonah",
        "Prophecy of Micheas": "Micah",
        "Prophecy of Nahum": "Nahum",
        "Prophecy of Habacuc": "Habakkuk",
        "Prophecy of Sophonias": "Zephania",
        "Prophecy of Aggeus": "Haggai",
        "Prophecy of Zacharias": "Zechariah",
        "Prophecy of Malachias": "Malachi",
        "First Book of Machabees": "Unknown",
        "Second Book of Machabees": "Unknown",
        "Gospel According to St. Matthew": "Matthew",
        "Gospel According to St. Mark": "Mark",
        "Gospel According to St. Luke": "Luke",
        "Gospel According to St. John": "John",
        "Acts of the Apostles": "Luke",
        "Epistle of St. Paul to the Romans": "Paul",
        "First Epistle of St. Paul to the Corinthians": "Paul",
        "Second Epistle of St. Paul to the Corinthians": "Paul",
        "Epistle of St. Paul to the Galatians": "Paul",
        "Epistle of St. Paul to the Ephesians": "Paul",
        "Epistle of St. Paul to the Philippians": "Paul",
        "Epistle of St. Paul to the Colossians": "Paul",
        "First Epistle of St. Paul to the Thessalonians": "Paul",
        "Second Epistle of St. Paul to the Thessalonians": "Paul",
        "First Epistle of St. Paul to Timothy": "Paul",
        "Second Epistle of St. Paul to Timothy": "Paul",
        "Epistle of St. Paul to Titus": "Paul",
        "Epistle of St. Paul to Philemon": "Paul",
        "Epistle of St. Paul to the Hebrews": "Paul",
        "Epistle of St. James the Apostle": "James",
        "First Epistle of St. Peter the Apostle": "Peter",
        "Second Epistle of St. Peter the Apostle": "Peter",
        "First Epistle of St. John the Apostle": "John",
        "Second Epistle of St. John the Apostle": "John",
        "Third Epistle of St. John the Apostle": "John",
        "Epistle of St. Jude the Apostle": "Jude",
        "Apocalypse of St. John the Apostle": "John",
    },
    "NEW_TESTAMENT": [
        "Gospel According to St. Matthew",
        "Gospel According to St. Mark",
        "Gospel According to St. Luke",
        "Gospel According to St. John",
        "Acts of the Apostles",
        "Epistle of St. Paul to the Romans",
        "First Epistle of St. Paul to the Corinthians",
        "Second Epistle of St. Paul to the Corinthians",
        "Epistle of St. Paul to the Galatians",
        "Epistle of St. Paul to the Ephesians",
        "Epistle of St. Paul to the Philippians",
        "Epistle of St. Paul to the Colossians",
        "First Epistle of St. Paul to the Thessalonians",
        "Second Epistle of St. Paul to the Thessalonians",
        "First Epistle of St. Paul to Timothy",
        "Second Epistle of St. Paul to Timothy",
        "Epistle of St. Paul to Titus",
        "Epistle of St. Paul to Philemon",
        "Epistle of St. Paul to the Hebrews",
        "Epistle of St. James the Apostle",
        "First Epistle of St. Peter the Apostle",
        "Second Epistle of St. Peter the Apostle",
        "First Epistle of St. John the Apostle",
        "Second Epistle of St. John the Apostle",
        "Third Epistle of St. John the Apostle",
        "Epistle of St. Jude the Apostle",
        "Apocalypse of St. John the Apostle",
    ],
    "WRITING_NODE_IDS": {
        "Genesis": "gen",
        "Exodus": "exo",
        "Leviticus": "lev",
        "Numbers": "num",
        "Deuteronomy": "deu",
        "Josue": "jos",
        "Judges": "judg",
        "Ruth": "ruth",
        "1 Samuel": "sam1",
        "2 Samuel": "sam2",
        "3 Kings": "kgs3",
        "4 Kings": "kgs4",
        "First Book of Paralipomenon": "chr1",
        "Second Book of Paralipomenon": "chr2",
        "1 Esdras": "esd1",
        "2 Esdras": "esd2",
        "Tobias": "tob",
        "Judith": "judith",
        "Esther": "est",
        "Job": "job",
        "Psalms": "psa",
        "Proverbs": "pro",
        "Ecclesiastes": "ecc",
        "Solomon's Canticle of Canticles": "song",
        "Wisdom": "wis",
        "Ecclesiasticus": "sir",
        "Prophecy of Isaias": "isa",
        "Prophecy of Jeremias": "jer",
        "Lamentations of Jeremias": "lam",
        "Prophecy of Baruch": "bar",
        "Prophecy of Ezechiel": "eze",
        "Prophecy of Daniel": "dan",
        "Prophecy of Osee": "hos",
        "Prophecy of Joel": "joel",
        "Prophecy of Amos": "amos",
        "Prophecy of Abdias": "obad",
        "Prophecy of Jonas": "jonah",
        "Prophecy of Micheas": "mic",
        "Prophecy of Nahum": "nah",
        "Prophecy of Habacuc": "hab",
        "Prophecy of Sophonias": "zeph",
        "Prophecy of Aggeus": "hag",
        "Prophecy of Zacharias": "zech",
        "Prophecy of Malachias": "mal",
        "First Book of Machabees": "mac1",
        "Second Book of Machabees": "mac2",
        "Gospel According to St. Matthew": "mat",
        "Gospel According to St. Mark": "mar",
        "Gospel According to St. Luke": "luk",
        "Gospel According to St. John": "joh",
        "Acts of the Apostles": "act",
        "Epistle of St. Paul to the Romans": "rom",
        "First Epistle of St. Paul to the Corinthians": "cor1",
        "Second Epistle of St. Paul to the Corinthians": "cor2",
        "Epistle of St. Paul to the Galatians": "gal",
        "Epistle of St. Paul to the Ephesians": "eph",
        "Epistle of St. Paul to the Philippians": "phi",
        "Epistle of St. Paul to the Colossians": "col",
        "First Epistle of St. Paul to the Thessalonians": "thes1",
        "Second Epistle of St. Paul to the Thessalonians": "thes2",
        "First Epistle of St. Paul to Timothy": "tim1",
        "Second Epistle of St. Paul to Timothy": "tim2",
        "Epistle of St. Paul to Titus": "tit",
        "Epistle of St. Paul to Philemon": "phm",
        "Epistle of St. Paul to the Hebrews": "heb",
        "Epistle of St. James the Apostle": "jam",
        "First Epistle of St. Peter the Apostle": "pet1",
        "Second Epistle of St. Peter the Apostle": "pet2",
        "First Epistle of St. John the Apostle": "joh1",
        "Second Epistle of St. John the Apostle": "joh2",
        "Third Epistle of St. John the Apostle": "joh3",
        "Epistle of St. Jude the Apostle": "jud",
        "Apocalypse of St. John the Apostle": "rev",
    },
}
